swagger: '2.0'
basePath: /v1
host: api.zoop.ws
info:
  title: Objetos Base
  version: "1.1"

securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []

tags:
  - name: 'Vendedor'
    description: 'Pessoas ou empresas que vendem dentro do seu marketplace.'
  - name: 'Comprador'
    description: 'Pessoas ou empresas que compram dentro do seu marketplace'
  - name: 'Token'
    description: Token de cartões de crédito
  - name: 'Saldo de Conta'
    description: Saldo de conta zoop
  - name: 'Disputa'
    description: Operações para consulta de disputas
  - name: 'Documento de Contestação'
    description: Operações upload e consulta de documentos de contestação

schemes:
  - https

paths:
  '/marketplaces/{marketplace_id}/sellers/{seller_id}/documents':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - $ref: '#/parameters/sellerId'

    post:
      tags:
        - 'Vendedor'
      summary: Criar documento de cadastro de vendedor
      description: ''
      operationId: addDocument
      consumes:
         - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: file
          type: file
          in: formData
          required: true
          format: binary
          description: Documento que será cadastrado
        - name: category
          in: formData
          type: string
          required: true
          description: Categoria do documento cadastrado
        - name: metadata
          in: formData
          type: string
          description: Metadados associados ao documento
        - name: description
          in: formData
          type: string
          description: Descrição do documento
      responses:
        '201':
          description: Documento criado com sucesso
          schema:
            $ref: '#/definitions/Document'
        '404':
          description: 'Marketplace/Vendedor/Documento não encontrado'
    get:
      tags:
        - 'Vendedor'
      summary: Listar documentos de um vendedor
      description: ''
      operationId: findSellerDocument
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/marketplaceId'
        - $ref: '#/parameters/sellerId'
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/sortParam'
        - $ref: '#/parameters/offsetParam'
        - $ref: '#/parameters/dateRangeParam'
        - $ref: '#/parameters/dateRangeGTParam'
        - $ref: '#/parameters/dateRangeGTEParam'
        - $ref: '#/parameters/dateRangeLTParam'
        - $ref: '#/parameters/dateRangeLTEParam'
      responses:
        '200':
          description: Documentos recuperados com sucesso
          schema:
            $ref: '#/definitions/Documents'
        '404':
          description: 'Marketplace/Vendedor não encontrado'
  '/marketplaces/{marketplace_id}/sellers/documents/{id}':

    put:
      tags:
        - 'Vendedor'
      summary: Atualiza os dados de um documento de um vendedor
      description: ''
      operationId: updateDocument
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/marketplaceId'
        - name: id
          in: path
          description: ID do documento
          required: true
          type: string
        - in: body
          name: body
          description: Document object
          required: true
          schema:
            $ref: '#/definitions/Document'
      responses:
        '200':
          description: Documento alterado com sucesso
          schema:
            $ref: '#/definitions/Document'
        '404':
          description: 'Marketplace/Documento não encontrado'
  '/merchant_category_codes':
    get:
      tags:
        - 'Vendedor'
      summary: Listar MCCs (Merchant Category Codes)
      description: ''
      operationId: ''
      produces:
        - application/json
      responses:
        '200':
          description: Operação realizada com sucesso
          schema:
            example: {
                resource: "list",
                uri: "/v1/merchant_category_codes",
                items: [
                            {
                                id: "1",
                                code: "5300",
                                category: "Alimentação",
                                description: "Atacado",
                                resource: "merchant_category_code"
                            }
                        ],
                        has_more: true,
                        limit: 100,
                        total_pages: 2,
                        page: 1,
                        offset: 0,
                        total: "103"
              }
  '/marketplaces/{marketplace_id}/sellers/individuals':
    post:
      tags:
        - 'Vendedor'
      summary: Criar novo vendedor do tipo indivíduo
      parameters:
        - $ref: '#/parameters/marketplaceId'
        - in: body
          name: body
          description: Individual object
          required: true
          schema:
            $ref: '#/definitions/Individual'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Vendedor cadastrado com sucesso
          schema:
            $ref: '#/responses/Individual'
        '404':
          description: 'Marketplace não encontrado'
        '400':
          description: 'Missing required param'
  '/marketplaces/{marketplace_id}/sellers/individuals/{seller_id}':
    put:
      tags:
        - 'Vendedor'
      summary: Alterar um vendedor do tipo indivíduo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/marketplaceId'
        - $ref: '#/parameters/sellerId'
        - in: body
          name: body
          description: Individual object
          required: true
          schema:
            $ref: '#/definitions/Individual'
      responses:
        '200':
          description: Vendedor alterado com sucesso
          schema:
            $ref: '#/responses/Individual'
        '404':
          description: 'Marketplace não encontrado'
        '400':
          description: 'Missing required param'
  '/marketplaces/{marketplace_id}/sellers/businesses':
    post:
      tags:
        - 'Vendedor'
      summary: Criar novo vendedor do tipo empresa
      parameters:
        - $ref: '#/parameters/marketplaceId'
        - in: body
          name: body
          description: Individual object
          required: true
          schema:
            $ref: '#/definitions/Business'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '201':
          description: Vendedor cadastrado com sucesso
          schema:
            $ref: '#/responses/Business'
        '404':
          description: 'Marketplace não encontrado'
        '400':
          description: 'Missing required param'
  '/marketplaces/{marketplace_id}/sellers/businesses/{seller_id}':
    put:
      tags:
        - 'Vendedor'
      summary: Alterar um vendedor do tipo empresa
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/marketplaceId'
        - $ref: '#/parameters/sellerId'
        - in: body
          name: body
          description: Business object
          required: true
          schema:
            $ref: '#/definitions/Business'
      responses:
        '200':
          description: Vendedor alterado com sucesso
          schema:
            $ref: '#/responses/Business'
        '404':
          description: 'Marketplace/Vendedor não encontrado'
        '400':
          description: 'Missing required param'
  '/v1/marketplaces/{marketplace_id}/sellers/{seller_id}':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - $ref: '#/parameters/sellerId'
    get:
      tags:
        - 'Vendedor'
      summary: Recupera detalhes de vendedor pelo id, os campos começando por "business_" são específicos para empresas.
      produces:
        - application/json
      responses:
        '200':
          description: Vendedor recuperado com sucesso
          schema:
            $ref: '#/responses/Business'
        '404':
          description: 'Marketplace/Vendedor não encontrado'
    delete:
      tags:
        - 'Vendedor'
      summary: Deleta um de vendedor pelo id
      produces:
        - application/json
      responses:
        '200':
          description: Vendedor deletado com sucesso
          schema:
            example:
              {
                'id': "17d9e827664b47509f12a082b6047e7a",
                'resource': 'seller',
                'type': 'individual',
                'deleted': true
              }
        '404':
          description: 'Marketplace/Vendedor não encontrado'
  '/marketplaces/{marketplace_id}/sellers':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - $ref: '#/parameters/limitParam'
      - $ref: '#/parameters/sortParam'
      - $ref: '#/parameters/offsetParam'
      - $ref: '#/parameters/dateRangeParam'
      - $ref: '#/parameters/dateRangeGTParam'
      - $ref: '#/parameters/dateRangeGTEParam'
      - $ref: '#/parameters/dateRangeLTParam'
      - $ref: '#/parameters/dateRangeLTEParam'
    get:
      tags:
        - 'Vendedor'
      summary: Listando vendedores
      produces:
        - application/json
      responses:
        '200':
          description: Vendedor recuperado com sucesso
          schema:
            $ref: '#/responses/Businesses'
        '404':
          description: 'Marketplace/Vendedor não encontrado'
  '/marketplaces/{marketplace_id}/sellers/search':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - in: query
        name: taxpayer_id
        type: string    
        description: CPF do vendedor
      - in: query
        name: ein
        type: string
        description: CNPJ do vendedor
    get:
      tags:
        - 'Vendedor'
      summary: Buscando de vendedor por CPF/CNPJ
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Vendedor encontrado com sucesso
          schema:
            $ref: '#/responses/Businesses'
        '404':
          description: 'Vendedor não encontrado'
        '400':
          description: 'Missing required parameter'
  '/marketplaces/{marketplace_id}/buyers':
    parameters:
      - $ref: '#/parameters/marketplaceId'
    post:
      tags:
        - 'Comprador'
      summary: 'Criar comprador'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: buyer data
          required: true
          schema:
            $ref: '#/definitions/BuyerRequest'
      responses:
        '200':
          description: Comprador criado com sucesso
          schema:
            $ref: "#/definitions/Buyer"
        '400':
          description: 'Missing required param'
        '404':
          description: Marketplace não encontrado
    get:
      tags:
        - 'Comprador'
      summary: 'Listar comprador por marketplace'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Comprador encontrado
        '404':
          description: Marketplace não encontrado
  '/marketplaces/{marketplace_id}/buyers/{buyer_id}':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - $ref: '#/parameters/buyerId'
    put:
      tags:
        - 'Comprador'
      summary: 'Alterar detalhes de comprador'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Comprador alterado com sucesso
          schema:
            $ref: "#/definitions/Buyer"
        '400':
          description: 'Missing required param'
        '404':
          description: Marketplace/Buyer não encontrado
    get:
      tags:
        - 'Comprador'
      summary: 'Recuperar detalhes de comprador'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Comprador alterado com sucesso
          schema:
            $ref: "#/definitions/Buyer"
        '404':
          description: Marketplace/Buyer não encontrado
    delete:
      tags:
        - 'Comprador'
      summary: 'Remover comprador pelo identificador'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Comprador removido com sucesso
        '404':
          description: Marketplace/Buyer não encontrado
  '/marketplaces/{marketplace_id}/buyers/search':
    parameters:
      - $ref: '#/parameters/marketplaceId'
    get:
      tags:
        - 'Comprador'
      summary: 'Buscar comprador por CPF/CNPJ'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Comprador encontrado
        '404':
          description: Marketplace não encontrado
  '/marketplaces/{marketplace_id}/sellers/{seller_id}/balances':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - name: seller_id
        in: path
        description: identificador do seller
        required: true
        type: string
    get:
      tags:
        - 'Saldo de Conta'
      summary: 'Recuperar saldo de conta por seller'
      description: 'Recupera o saldo corrente e saldo total de conta'
      produces:
        - application/json
      responses:
        '200':
          description: Saldo recuperado com sucesso
        '404':
          description: Marketplace/Seller não encontrado
  '/marketplaces/{marketplace_id}/sellers/{seller_id}/balances/all':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - name: seller_id
        in: path
        description: identificador do seller
        required: true
        type: string
    get:
      tags:
        - 'Saldo de Conta'
      summary: 'Lista contas por seller'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Saldo recuperado com sucesso
        '404':
          description: Marketplace/Seller não encontrado
  '/marketplaces/{marketplace_id}/buyers/{buyer_id}/balances':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - $ref: '#/parameters/buyerId'
    get:
      tags:
        - 'Saldo de Conta'
      summary: 'Lista contas por buyer'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Saldo recuperado com sucesso
        '404':
          description: Marketplace/Buyer não encontrado
  '/marketplaces/{marketplace_id}/balances/{balance_id}/history':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - name: balance_id
        in: path
        description: identificador da conta
        required: true
        type: string
    get:
      tags:
        - 'Saldo de Conta'
      summary: 'Listar histórico de lançamentos pelo identificador da conta'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Histórico recuperado com sucesso
        '404':
          description: Marketplace/Saldo não encontrado

  '/marketplaces/{marketplace_id}/sellers/{seller_id}/balances/history':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - name: seller_id
        in: path
        description: identificador do seller
        required: true
        type: string
    get:
      tags:
        - 'Saldo de Conta'
      summary: 'Listar histórico de lançamentos de conta por seller'
      description: 'Listagem de histórico da conta principal do seller'
      produces:
        - application/json
      responses:
        '200':
          description: Histórico recuperado com sucesso
        '404':
          description: Marketplace/Seller não encontrado

  '/marketplaces/{marketplace_id}/buyers/{buyer_id}/balances/history':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - $ref: '#/parameters/buyerId'
    get:
      tags:
        - 'Saldo de Conta'
      summary: 'Listar histórico de lançamentos de conta por buyer'
      description: 'Listagem de histórico da conta principal do buyer'
      produces:
        - application/json
      responses:
        '200':
          description: Histórico recuperado com sucesso
        '404':
          description: Marketplace/Seller não encontrado
  '/marketplaces/{marketplace_id}/cards/tokens':
    parameters:
      - $ref: '#/parameters/marketplaceId'
    post:
      tags:
        - 'Token'
      summary: 'Criar novo token de cartão'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: token data
          required: true
          schema:
            $ref: '#/definitions/TokenCardRequest'
      responses:
        '200':
          description: Token de cartão criado com sucesso
        '400':
          description: Requisição/Parâmetros invalidos
        '404':
          description: Marketplace/ não encontrado
  '/marketplaces/{marketplace_id}/bank_accounts/tokens':
    parameters:
      - $ref: '#/parameters/marketplaceId'
    post:
      tags:
        - 'Token'
      summary: 'Criar novo token de conta bancária'
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: Token de cartão criado com sucesso
        '400':
          description: Requisição/Parâmetros invalidos
        '404':
          description: Marketplace não encontrado
      parameters:
        - in: body
          name: token data
          required: true
          schema:
            $ref: '#/definitions/BankAccountRequest'
  '/marketplaces/{marketplace_id}/tokens/{token_id}':
    parameters:
      - $ref: '#/parameters/marketplaceId'
      - name: token_id
        in: path
        description: identificador do token
        required: true
        type: string
    get:
      tags:
        - 'Token'
      summary: 'Recuperar detalhes de token de cartão/conta bancária'
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Token recuperado com sucesso
        '404':
          description: Marketplace/Token não encontrado
definitions:
  $ref: ./definitions.yaml
parameters:
  $ref: ./parameters.yaml
responses:
  $ref: ./responses.yaml
  