swagger: '2.0'
host: api.zoop.ws
info:
  description: API que gerencia o processo de disputa das transações Zoop.
  version: '1.0'
  title: Zoop-Dispute-API
  contact:
    name: Zoop
    url: 'http://www.zoop.co'
    email: contato@zoop.co
  license:
    name: 'License '
    url: 'http://www.zoop.co'
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []

schemes:
  - https

tags:
  - name: Metodos de Disputa
    description: Operações para consulta de disputas
  - name: Recurso de Documento de Contestação
    description: Operações upload e consulta de documentos de contestação
    
paths:
  '/v1/marketplaces/{marketplace_id}/disputes':
    get:
      tags:
        - Metodos de Disputa
      summary: Listagem de Disputas com paginação
      description: Lista as disputas de um Marketplace com opção de filtros e paginação.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: marketplace_id
          in: path
          description: marketplace_id
          required: true
          type: string
        - name: status
          in: query
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          enum:
            - Pending
            - AuthorizedChargeback
            - Waiting Contestation
            - Finalized
        - name: start_date
          in: query
          description: yyyy-mm-dd
          required: false
          type: string
        - name: end_date
          in: query
          description: yyyy-mm-dd
          required: false
          type: string
        - name: page
          in: query
          description: 'Page offset (Default: 0)'
          required: false
          type: integer
          format: int32
        - name: limit
          in: query
          description: 'Page limit (Default/Max: 100)'
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: Lista de disputas
          schema:
            $ref: '#/definitions/DisputeTO'
        '401':
          description: Falha no processo de autenticação
        '403':
          description: Sem autorização para acessar o recurso
        '404':
          description: Marketplace não encontrado
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Erro de operação interna
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/v1/marketplaces/{marketplace_id}/disputes/{dispute_id}':
    get:
      tags:
        - Metodos de Disputa
      summary: Consulta Disputa
      description: Consulta disputa de um Marketplace por seu ID.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: marketplace_id
          in: path
          description: marketplace_id
          required: true
          type: string
        - name: dispute_id
          in: path
          description: dispute_id
          required: true
          type: string
      responses:
        '200':
          description: Disputa encontrada
          schema:
            $ref: '#/definitions/DisputeTO'
        '401':
          description: Falha no processo de autenticação
        '403':
          description: Sem autorização para acessar o recurso
        '404':
          description: Disputa não encontrada
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Erro de operação interna
          schema:
            $ref: '#/definitions/ErrorResponse'
  '/v1/marketplaces/{marketplace_id}/disputes/{dispute_id}/document':
    get:
      tags:
        - Recurso de Documento de Contestação
      summary: Download do Arquivo de Disputa
      description: Realiza o download do arquivo de disputa cadastrado.
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: marketplace_id
          in: path
          description: marketplace_id
          required: true
          type: string
        - name: dispute_id
          in: path
          description: dispute_id
          required: true
          type: string
      responses:
        '200':
          description: Download realizado com sucesso
          schema:
            $ref: '#/definitions/DisputeTO'
        '401':
          description: Falha no processo de autenticação
        '403':
          description: Sem autorização para acessar o recurso
        '404':
          description: Marketplace não encontrado
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Erro de operação interna
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      tags:
        - Recurso de Documento de Contestação
      summary: Inclusão de Documento
      description: >-
        Permite incluir documentos no prazo de até 10 dias após a data de
        criação da disputa, ao incluir um novo documento este substitui
        automaticamente o anterior. Os formatos válidos de documentos são PDF,
        JPEG e TIFF, como tamanho máximo de 7MB e resolução de 200 x 200.
      consumes:
        - multipart/form-data
      produces:
        - '*/*'
      parameters:
        - name: marketplace_id
          in: path
          description: marketplace_id
          required: true
          type: string
        - name: dispute_id
          in: path
          description: dispute_id
          required: true
          type: string
        - name: uploadFile
          in: formData
          description: uploadFile
          required: true
          type: file
      responses:
        '200':
          description: Documento incluso com sucesso
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Falha no processo de autenticação
        '403':
          description: Sem autorização para acessar o recurso
        '404':
          description: Marketplace não encontrado
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Erro de operação interna
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      tags:
        - Recurso de Documento de Contestação
      summary: Remove documento de contestação
      description: >-
        Remove um documento de contestação da disputa somente se ainda não tiver
        sido acatada pela Adquirente.
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: marketplace_id
          in: path
          description: marketplace_id
          required: true
          type: string
        - name: dispute_id
          in: path
          description: dispute_id
          required: true
          type: string
      responses:
        '200':
          description: Documento removido com sucesso
          schema:
            $ref: '#/definitions/DisputeTO'
        '204':
          description: No Content
        '401':
          description: Falha no processo de autenticação
        '403':
          description: Sem autorização para acessar o recurso
        '404':
          description: Marketplace não encontrado
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: Erro de operação interna
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  DisputeTO:
    type: object
    properties:
      amount:
        type: number
        format: double
      authorization:
        type: string
      card_holder:
        type: string
      card_type:
        type: string
      desc_reason:
        type: string
      dispute_date:
        type: string
        format: date-time
      expiration_date:
        type: string
        example: 'yyyy-MM-dd HH:mm:ss.SSSZ'
      has_associate_file:
        type: boolean
      id:
        type: string
      marketplace_id:
        type: string
      marketplace_name:
        type: string
      mask_credit_number:
        type: string
      merchant:
        type: string
      nsu:
        type: string
      purchase_date:
        type: string
        format: date-time
      reason:
        type: string
      reference_id:
        type: string
      status:
        type: string
      tid:
        type: string
      transaction_id:
        type: string
      updated_at:
        type: string
        example: 'yyyy-MM-dd HH:mm:ss.SSSZ'
  DisputeTORequest:
    type: object
    required:
      - acquirer
      - amount
      - card_type
      - case_number
      - dispute_date
      - nsu
      - process
      - purchase_date
      - reason
      - result
    properties:
      acquirer:
        type: string
      amount:
        type: number
        format: double
      authorization:
        type: string
      card_holder:
        type: string
      card_type:
        type: string
      case_number:
        type: string
      desc_reason:
        type: string
      dispute_date:
        type: string
        description: yyyy-mm-dd
      mask_credit_number:
        type: string
      merchant:
        type: string
      nsu:
        type: string
      process:
        type: string
      purchase_amount:
        type: number
        format: double
      purchase_date:
        type: string
        description: yyyy-mm-dd
      reason:
        type: string
      result:
        type: string
      tid:
        type: string
  Error:
    type: object
    properties:
      category:
        type: string
      message:
        type: string
      status:
        type: string
      status_code:
        type: integer
        format: int32
      type:
        type: string
  ErrorResponse:
    type: object
    properties:
      error:
        $ref: '#/definitions/Error'
  PagedResult:
    type: object
    properties:
      elements:
        type: array
        items:
          type: object
      limit:
        type: integer
        format: int32
      offset:
        type: integer
        format: int32
      totalElements:
        type: integer
        format: int64
  PagedResult«DisputeTO»:
    type: object
    properties:
      elements:
        type: array
        items:
          $ref: '#/definitions/DisputeTO'
      limit:
        type: integer
        format: int32
      offset:
        type: integer
        format: int32
      totalElements:
        type: integer
        format: int64
