swagger: "2.0"
info:
  description: "API de Recebíveis da Zoop"
  version: "1.0.0"
  title: "API de Recebível da Zoop"
host: "api.zoop.ws"
basePath: "/v1"
tags:
- name: "Recebíveis"
  description: "API de Recebível"
schemes:
- "https"
paths:
  /marketplaces/{marketplaceId}/sellers/{sellerId}/receivables:
    get:
      summary: Retona uma listagem de recebíveis
      parameters:
      - name: marketplaceId
        type: "string"
        in: path
        required: true
        description: ID do Marketplace.
      - name: sellerId
        type: "string"
        in: path
        required: true
        description: ID do Seller.
      - in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/ReceivableRequest"
      responses:
        200:
          description: "Sucesso na recupareção da listagem de Recebíveis"
          schema:
            $ref: "#/definitions/ReceivableResponse"
        400:
          description: "Requisição inválida"
        404:
          description: "Marketplace, Seller ou Recebíveis não encontrado(s)"

definitions:
  ReceivableRequest:
    type: object
    properties:
      prepayable_for:
        type: string
        format: date
        example: '2019-05-30'
        description: "Filtro utilizado para recuperar os Recebíveis que podem ser antecipados, a partir data informada. Ao passar o valor, não é necessária a utilização das aspas, ex: `prepayable_for=2019-05-30`"
      expected_on_range:
        type: string
        format: date
        example: '2019-05-30'
      created_at_range:
        type: string
        format: date
        example: '2019-05-30'
      paid_at_range:
        type: string
        format: date
        example: '2019-05-30'
      status:
        type: string
        example: "pending"
      prepaid:
        type: number
        example: 1
      id_original_receivable:
        type: string
        example: "e8caee4290f28d4c96c451d93c2d0000"
      sort:
        type: string
        example: "DESC"

  ReceivableResponse:
    type: object
    properties:
      resource:
        type: string
      uri:
        type: string
      items:
        type: array
        items:
          $ref: "#/definitions/Receivable"
      has_more:
        type: boolean
      limit:
        type: integer
      total_pages:
        type: integer
      page:
        type: integer
      offset:
        type: integer
      total:
        type: string
      query_count:
        type: string

  Receivable:
    type: object
    properties:
      id:
        type: string
      resource:
        type: string
      status:
        type: string
      recipient:
        type: string
      transaction:
        type: string
      split_rule:
        type: object
      installment:
        type: string
        example: "3"
      liable:
        type: boolean
      amount:
        type: number
      gross_amount:
        type: number
      anticipation_fee:
        type: number
      paid_at:
        type: string
        format: date
        example: "2019-05-30"
      created_at:
        type: string
        format: date
        example: "2019-05-30"
      transaction_created_at:
        type: string
        format: date
        example: "2019-05-30"
      canceled_at:
        type: string
        format: date
        example: "2019-05-30"
      expected_on:
        type: string
        format: date
        example: "2019-05-30"
      authorization_code:
        type: string
      id_original_receivable:
        type: string
      prepaid:
        type: number
        example: 1
